fix noResult showing on search when typing search text and change people tiles ratio
KonradBauer/movies-browser pull request #40
Opened 2023-04-04 20:27 UTC by KonradBauer

Check this changes - type sth on people or movies input. Tiles is no more too much width.

2023-04-04 21:01 UTC, piotrpaczuski requested changes
Change things, which I wrote in comments to lines.

2023-04-04 21:01 UTC, piotrpaczuski commented on src/features/Input/index.js
> -    dispatch(changeMoviesSearchText(""));
You unnecessarily moved this dispatch to setTimeout below.

2023-04-04 21:01 UTC, piotrpaczuski commented on src/features/Input/index.js
> -    dispatch(changePeopleSearchText(""));
You unnecessarily moved this dispatch to setTimeout below.

2023-04-04 21:01 UTC, piotrpaczuski commented on src/App.js
> +    dispatch(fetchSearchPeople());
This dispatch is unneccessary, because he was added in the other pull request.

2023-04-04 21:01 UTC, piotrpaczuski commented on src/App.js
> +import { fetchSearchPeople, selectSearchPeopleStatus } from "./features/peoples/searchPeopleSlice";
From this import you can delete fetchSearchPeople.

2023-04-04 21:54 UTC, KonradBauer commented on src/App.js
> +    dispatch(fetchSearchPeople());
I fix requested changes, check it out

2023-04-04 22:25 UTC, piotrpaczuski approved these changes
After your changes everything works, when I mess up the link by adding the wrong id, an error page is shown. Well done.

2023-04-05 16:24 UTC, florekdeveloper approved these changes
Everything works well, great job :)

2023-04-05 17:18 UTC, merged